### PR TITLE
fix co2 values

### PR DESCRIPTION
**Pull request by SKruthoff**

### CODE REVIEW

**Comment by SKruthoff** [comment]
When runnning ecoinvent I noticed that we are not able to generate the emission data, so I updated the code. It is one line change that does not work in the end.

**Comment by ysherstyuk** [comment]
So one line code is not a fix?

**Comment by SKruthoff** [comment]
I think my initial message was confusing. This one line of code is the fix for the issue.

**Review by ysherstyuk — APPROVED** [review]
LGTM

**Pull request merged**
